
spring:
  profiles:
    active: local
  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.learn.english.entity

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥，长度必须大于等于128个字节
  secret: abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzqwertyuiopas
  # 令牌有效期（默认30分钟）
  expireTime: 30
