server:
  port: 5000

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn_english?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: LEHikariPool
      connection-test-query: SELECT 1


user:
  password:
    open: false
    max-retry-count: 5
    lock-time: 300 # minutes

# 词典配置
dict:
  youdao:
    api-url: https://openapi.youdao.com/api
    app-id: xxx
    app-key: xxx

# OpenAi 配置
openai:
  prompt: "请充当一名翻译官，根据给出的英文单词，生成3个简单例句，包含中文翻译。生成格式为json，具体格式如下：[{\"en\":\"xxx\",\"zh\":\"xxx\"},{\"en\":\"xxx\",\"zh\":\"xxx\"}]除此之外不需要任何内容。"
  api-url: https://api.openai.com/v1/chat/completions
  api-key: sk-xxx
  model: gpt-3.5-turbo
